apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: capstone-hello-deployment
  labels:
    app: capstone-hello
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxUnavailable: 50%
        maxSurge: 1
  replicas: 4
  selector:
    matchLabels:
      app: capstone-hello
  template:
    metadata:
      labels:
        app: capstone-hello
    spec:
      containers:
        - name: capstone-hello
          imagePullPolicy: Always
          image: IMAGE
          ports:
            - containerPort: 80
          readinessProbe:
              httpGet:
                path: /
                port: 80
              periodSeconds: 10
              timeoutSeconds: 5
              successThreshold: 1
              failureThreshold: 10